version: '3'

services:
  app:
    build: 
      context: node
      dockerfile: Dockerfile
    container_name: app
    networks:
      - node-network
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /docker-entrypoint-initdb.d/initdb.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/docker-init/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on: 
      - db
      - app



networks:
  node-network:
    driver: bridge